In [1]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]
data


[[1, 2], [3, 4]]

In [4]:
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [6]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [14]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5106, 0.7902],
        [0.4726, 0.4938]]) 



In [15]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7577, 0.4732, 0.8235],
        [0.0394, 0.9597, 0.7662]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [16]:
tensor = torch.rand(3, 4)
print(f"tensor: {tensor}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor: tensor([[0.8987, 0.2706, 0.2849, 0.2859],
        [0.9790, 0.3002, 0.0500, 0.6576],
        [0.5809, 0.2662, 0.9813, 0.8345]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [17]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

/home/js/anaconda3/envs/langGraph/lib/python3.11/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


In [33]:
tensor = torch.ones(4, 4)
tensor[:,1] = 2
tensor[2,:] = 3
print(tensor)
print(f"tensor.shape: {tensor.shape}")

tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [3., 3., 3., 3.],
        [1., 2., 1., 1.]])
tensor.shape: torch.Size([4, 4])


In [30]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(f"t1.shape: {t1.shape}")

tensor([[1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.]])
t1.shape: torch.Size([4, 12])


In [31]:
t0 = torch.cat([tensor, tensor, tensor], dim=0)
print(t0)
print(f"t0.shape: {t0.shape}")

tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]])
t0.shape: torch.Size([12, 4])


In [34]:
# 요소별 곱(element-wise product)을 계산합니다
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# 다른 문법:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [9., 9., 9., 9.],
        [1., 4., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [9., 9., 9., 9.],
        [1., 4., 1., 1.]])


In [37]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [39]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor)} \n")
# 다른 문법:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [48]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [49]:
t.add(1)

tensor([2., 2., 2., 2., 2.])

In [50]:
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [51]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [52]:
n  

array([2., 2., 2., 2., 2.], dtype=float32)

In [54]:
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [55]:
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [56]:
np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
